[package]
name = "command"
version = "0.1.0"
edition = "2021"


[dependencies.argh]
git = "https://github.com/google/argh"
default-features = false
features = ["help"]

[dependencies.rayon]
version = "1.10.0"
default-features = false
