name: Rust Build

on:
  push:
    branches:
      - main  # 或者你使用的其他分支
  pull_request:
    branches:
      - main  # 或者你使用的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # 或者指定其他版本，如 nightly
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
